# Generated by Django 2.0 on 2017-12-10 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
