# Generated by Django 2.0 on 2017-12-10 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='comments',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
