# Generated by Django 2.0 on 2017-12-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20171211_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
