# Generated by Django 2.0 on 2017-12-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20171212_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackModel',
            new_name='Feedback',
        ),
    ]
