# Generated by Django 2.0 on 2018-01-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20171217_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
